### ISSUE TITLE
Bignum: Support LLP64 ABI

### ISSUE THREAD

**Issue by okuoku** [higepon/mosh#111]
Win64 is LLP64 thus `long` is 32bits. This logic is not correct:

https://github.com/higepon/mosh/blob/73cac6e595a6457e26cdfc420a2278c9fd29be6a/src/Bignum.h#L186-L223

`sizeof(intptr_t)` does not always match with `sizeof(long)` thus we need separate `MOSH_BIGNUM_SIZEOF_LONG` macro.

This was caught by this warning and can be disabled once it fixed:

```
include\gmp.h(1785): warning C4244: 'return': conversion from 'mp_limb_t' to 'unsigned long', possible loss of data
```

**Comment by higepon** [comment]
Thanks for the catch!
