### ISSUE TITLE
R7RS MS1: Pass chibi-scheme R7RS test suite

### ISSUE THREAD

**Issue by higepon** [higepon/mosh#119]
Originally from https://github.com/higepon/mosh/issues/49#issuecomment-1241926615.

**MS1**: Pass chibi-scheme R7RS test suite https://github.com/ashinn/chibi-scheme/blob/master/tests/r7rs-tests.scm

- Backport nmosh R7RS standard libraries
- Implement Reader extensions; nmosh did the most and only remaining is `|symbol|` IIRC
- Fix bugs found by chibi-scheme test suite

When MS1 completed, we can run R7RS Scheme programs that uses `(scheme base)` and its friends. 

## P0: Must fix
- [x] (SKIPPED (test #(1 1 2 4 5) (let ((vec (vector 1 2 3 4 5))) (vector-copy! vec 1 vec 0 2) vec)))
- [x] (SKIPPED (test-error (apply +)))
- [x] (SKIPPED (test 'abc (read (open-input-string "#!fold-case ABC"))))
- [x] (SKIPPED (test 'ABC (read (open-input-string "#!fold-case #!no-fold-case ABC"))))
- [x] (SKIPPED (test '(a . b) (read (open-input-string "(a . b #;c)"))))
- [x] (SKIPPED (test-read-error "(#;a . b)"))
- [x] (SKIPPED (test-read-error "(a . #;b)"))
- [x] (SKIPPED (test-read-error "(#;x #;y . z)"))

## P1: Want to fix
- [x] (SKIPPED (test #t (promise? (delay (+ 2 2)))))
- [x] (SKIPPED (test #t (promise? (make-promise (+ 2 2)))))
- [x] (SKIPPED (test #t (let ((x (delay (+ 2 2)))) (force x) (promise? x))))
- [x] (SKIPPED (test #t (let ((x (make-promise (+ 2 2)))) (force x) (promise? x))))
- [x] (SKIPPED (test 4 (force (make-promise (+ 2 2)))))
- [x] (SKIPPED (test 4 (force (make-promise (make-promise (+ 2 2))))))
- [x] (SKIPPED (test-write-syntax "|\"|" '|\"|))
- [x] (SKIPPED (test '_ (underscore foo)))
- [x] (SKIPPED (test '(2 0 many) (list (count-to-2 a b) (count-to-2) (count-to-2 a b c d))))
- [x] (SKIPPED (test '(2 0 fail fail) (list (count-to-2_ _ _) (count-to-2_) (count-to-2_ a b) (count-to-2_ a b c d))))
- [x] (SKIPPED (let () (define x 1) (let-syntax () (define x 2) #f) (test 1 x)))

## P2: Would be great to fix.
- [ ] (SKIPPED (let () (define-syntax elli-lit-1 (syntax-rules ... (...) ((_ x) '(x ...)))) (test '(100 ...) (elli-lit-1 100))))
- [ ] (SKIPPED (test-precision "-1.7976931348623157e+308" "-inf.0"))
- [ ] (SKIPPED (test-precision "1.976262583364986e-323" "1.97626258336499e-323" "2.0e-323" "0.0"))
- [ ] (SKIPPED (test-precision "1.7976931348623157e+308" "+inf.0"))
- [x] (SKIPPED (test 0.0 (atan 0.0 1.0)))
- [x] (SKIPPED (test -0.0 (atan -0.0 1.0)))
- [x] (SKIPPED (test 0.785398163397448 (atan 1.0 1.0)))
- [x] (SKIPPED (test 1.5707963267949 (atan 1.0 0.0)))
- [x] (SKIPPED (test 2.35619449019234 (atan 1.0 -1.0)))
- [x] (SKIPPED (test 3.14159265358979 (atan 0.0 -1.0)))
- [x] (SKIPPED (test -3.14159265358979 (atan -0.0 -1.0)))
- [x] (SKIPPED (test -2.35619449019234 (atan -1.0 -1.0)))
- [x] (SKIPPED (test -1.5707963267949 (atan -1.0 0.0)))
- [x] (SKIPPED (test -0.785398163397448 (atan -1.0 1.0)))
- [ ] (SKIPPED (test 0.0+1.0i (sqrt -1.0-0.0i)))
- [ ] (SKIPPED (test #f (string->number "1 2")))
- [ ] (SKIPPED (test #t (read-error? (guard (exn (else exn)) (read (open-input-string "\""))))))
- [ ] (SKIPPED (test 'error (let ((in (open-input-string "abc"))) (close-input-port in) (guard (exn (else 'error)) (read-char in)))))
- [ ] (SKIPPED (test #t (char-ready? (open-input-string "42"))))
- [ ] (SKIPPED (test "((1 2 3) (1 2 3))" (let ((out (open-output-string)) (x (list 1 2 3))) (write (list x x) out) (get-output-string out))))
- [ ] (SKIPPED (test "line 1\n\nline 3\n" (read (open-input-string "\"line 1\\ \t \n \t \n\nline 3\n\""))))

**Comment by higepon** [comment]
With https://github.com/higepon/mosh/pull/117, now r7rs-tests.scm is enabled in make check. 

```
[  PASSED  ] 1174 passed, 42 skipped.
```

There are still 42 skip(s) and I categorized them into 3 buckets. Please let me know what you think.
Also I'd appreciate it if you could help and fix some of them.


To @okuoku 
- Do you have R7RS promise implementation we can use?
- Do you have atan implementation we can use?
- Any failures you want me prioritize to fix?


## P0: Must fix
```
  (SKIPPED (test #(1 1 2 4 5) (let ((vec (vector 1 2 3 4 5))) (vector-copy! vec 1 vec 0 2) vec)))
  (SKIPPED (test-error (apply +)))
  (SKIPPED (test 'abc (read (open-input-string "#!fold-case ABC"))))
  (SKIPPED (test 'ABC (read (open-input-string "#!fold-case #!no-fold-case ABC"))))
  (SKIPPED (test '(a . b) (read (open-input-string "(a . b #;c)"))))
  (SKIPPED (test-read-error "(#;a . b)"))
  (SKIPPED (test-read-error "(a . #;b)"))
  (SKIPPED (test-read-error "(#;x #;y . z)"))
```

## P1: Want to fix
```
  (SKIPPED (test #t (promise? (delay (+ 2 2)))))
  (SKIPPED (test #t (promise? (make-promise (+ 2 2)))))
  (SKIPPED (test #t (let ((x (delay (+ 2 2)))) (force x) (promise? x))))
  (SKIPPED (test #t (let ((x (make-promise (+ 2 2)))) (force x) (promise? x))))
  (SKIPPED (test 4 (force (make-promise (+ 2 2)))))
  (SKIPPED (test 4 (force (make-promise (make-promise (+ 2 2))))))
  (SKIPPED (test-write-syntax "|\"|" '|\"|))
  (SKIPPED (test '_ (underscore foo)))
  (SKIPPED (test '(2 0 many) (list (count-to-2 a b) (count-to-2) (count-to-2 a b c d))))
  (SKIPPED (test '(2 0 fail fail) (list (count-to-2_ _ _) (count-to-2_) (count-to-2_ a b) (count-to-2_ a b c d))))
  (SKIPPED (let () (define x 1) (let-syntax () (define x 2) #f) (test 1 x)))
  (SKIPPED (let () (define-syntax elli-lit-1 (syntax-rules ... (...) ((_ x) '(x ...)))) (test '(100 ...) (elli-lit-1 100))))
```

## P2: Would be great to fix.
```
  (SKIPPED (test-precision "-1.7976931348623157e+308" "-inf.0"))
  (SKIPPED (test-precision "1.976262583364986e-323" "1.97626258336499e-323" "2.0e-323" "0.0"))
  (SKIPPED (test-precision "1.7976931348623157e+308" "+inf.0"))
  (SKIPPED (test 0.0 (atan 0.0 1.0)))
  (SKIPPED (test -0.0 (atan -0.0 1.0)))
  (SKIPPED (test 0.785398163397448 (atan 1.0 1.0)))
  (SKIPPED (test 1.5707963267949 (atan 1.0 0.0)))
  (SKIPPED (test 2.35619449019234 (atan 1.0 -1.0)))
  (SKIPPED (test 3.14159265358979 (atan 0.0 -1.0)))
  (SKIPPED (test -3.14159265358979 (atan -0.0 -1.0)))
  (SKIPPED (test -2.35619449019234 (atan -1.0 -1.0)))
  (SKIPPED (test -1.5707963267949 (atan -1.0 0.0)))
  (SKIPPED (test -0.785398163397448 (atan -1.0 1.0)))
  (SKIPPED (test 0.0+1.0i (sqrt -1.0-0.0i)))
  (SKIPPED (test #f (string->number "1 2")))
  (SKIPPED (test #t (read-error? (guard (exn (else exn)) (read (open-input-string "\""))))))
  (SKIPPED (test 'error (let ((in (open-input-string "abc"))) (close-input-port in) (guard (exn (else 'error)) (read-char in)))))
  (SKIPPED (test #t (char-ready? (open-input-string "42"))))
  (SKIPPED (test "((1 2 3) (1 2 3))" (let ((out (open-output-string)) (x (list 1 2 3))) (write (list x x) out) (get-output-string out))))
  (SKIPPED (test "line 1\n\nline 3\n" (read (open-input-string "\"line 1\\ \t \n \t \n\nline 3\n\""))))
```

**Comment by okuoku** [comment]
> Do you have R7RS promise implementation we can use?

The R7RS document includes polyfill like this:

https://github.com/okuoku/yuni/blob/40ebfe8f13b859d18bbde2ba97b99f1ff1ec45ea/lib-r7c/r7c-report/misc/lazy.sls#L10-L46

https://nacl-ltd.github.io/2016/05/31/delay-force.html (Ja) is a nice write up around the topic. Note that SRFI-45 refers `delay-force` as `lazy`.

> Do you have atan implementation we can use?

Chibi-scheme has `atan` implementation with atan1

https://github.com/ashinn/chibi-scheme/blob/05ee42804a900c21bd189a506578d8ca1669c0e8/lib/init-7.scm#L1451-L1465

But, since we're on C++, `std::atan2` is mandated so we should use native implementation. Chibi-scheme implementation requires correct handling of `-0.0`.

**Comment by higepon** [comment]
> The R7RS document includes polyfill like this:

Thank yeah. I noticed that the code is not completed. For example signature of make-promise is different.
Let me look into it.

**Comment by higepon** [comment]
P0 and P1 have been fixed.

**Comment by higepon** [comment]
I'm surprised at this bug :)
https://github.com/higepon/mosh/pull/136/files#diff-8452647f5ca8273d938c188cd226928357ec83c21b2121d303157ca4bd1659cfL106

**Comment by higepon** [comment]
I'm closing this. We have still 10 failures but I don't think they are critical. Will file a separate issue for them.
Thank you everyone. We're moving to the next milestone.

```
  (SKIPPED (let () (define-syntax elli-lit-1 (syntax-rules ... (...) ((_ x) '(x ...)))) (test '(100 ...) (elli-lit-1 100))))
  (SKIPPED (test #f (string->number "1 2")))
  (SKIPPED (test #t (read-error? (guard (exn (else exn)) (read (open-input-string "\""))))))
  (SKIPPED (test 'error (let ((in (open-input-string "abc"))) (close-input-port in) (guard (exn (else 'error)) (read-char in)))))
  (SKIPPED (test #t (char-ready? (open-input-string "42"))))
  (SKIPPED (test "((1 2 3) (1 2 3))" (let ((out (open-output-string)) (x (list 1 2 3))) (write (list x x) out) (get-output-string out))))
  (SKIPPED (test "line 1\n\nline 3\n" (read (open-input-string "\"line 1\\ \t \n \t \n\nline 3\n\""))))
  (SKIPPED (test-precision "-1.7976931348623157e+308" "-inf.0"))
  (SKIPPED (test-precision "1.976262583364986e-323" "1.97626258336499e-323" "2.0e-323" "0.0"))
  (SKIPPED (test-precision "1.7976931348623157e+308" "+inf.0"))

[  PASSED  ] 1210 passed, 10 skipped. 
```
