### ISSUE TITLE
R7RS MS2: Implement R7RS library handling

### ISSUE THREAD

**Issue by higepon** [higepon/mosh#120]
Originally from https://github.com/higepon/mosh/issues/49#issuecomment-1241926615.

**MS2**: Implement R7RS library handling

- Implement R7RS library constructs; `define-library` `include` `include-ci` `cond-expand`
- Implement ACC for R7RS libraries

When MS2 completed, we can import R7RS libraries such as https://github.com/scheme-requests-for-implementation/srfi-233 directly.

**Comment by higepon** [comment]
#### Ideas & steps
- Write a converter R6RS library => R7RS library.
   - Have 1 test set.
   - Probably write it outside of psyntax world first.
     - But maybe with syntax-match?
   - Embed it into psyntax.
 - Does psyntax inluce work as R7RS include?

**Comment by higepon** [comment]
- https://github.com/higepon/mosh/pull/141

**Comment by lassik** [comment]
A version of psyntax that handles both R6RS and R7RS could potentially be useful for other implementations, too.

**Comment by higepon** [comment]
Great point! I think so. I hope this route works well.

**Comment by higepon** [comment]
## R7RS to R6RS library converter design notes
### include
#### R7RS expectations
```
(include 〈string1〉 〈string2〉 . . . ) syntax
(include-ci 〈string1〉 〈string2〉 . . . ) syntax
```
> effectively re-
place the include or include-ci expression with a begin
expression containing what was read from the files. 

#### How we do it in psyntax
- psyntax
  - It has ```(include <string>)```. The behaviour matches R7RS.
- We should rewrite ```(include s1 s2 ...)``` to multiple ```(include s)```.
- We should support ```(include path)``` where path="x.scm" and x.scm is locating in the same directory as the including library.

### file extension
#### Expectations
- ```.sls``` for R6RS library (supported)
- ```.sds``` for R7RS library + (include .scm R5RS library) (not supported)
- .mosh.sds > .sds (not supported)
  - I think I saw this pattern but don't remember.
#### How we do it?
- psyntax
  - Extensions: ```'(".sls" ".ss" ".scm")``` are supported as extension of a library file.
  - Add ```.sds``` here.
  - How do we treat .scm?
    - When psyntax sees ```(import (mosh test))```, it searches mosh/test.sds, mosh/test.sls, mosh/test.scm in order in the load path?

### library cache
- The existing library cache system should work OK except ```include```.
- Ideally we should recreate cache when included file is newer than cache file.
  - I think we can go w/o this. library developer can use --disable-acc.

### cond-expand
- either the library converter or psyntax should be able to handle it easilty.

@okuoku is there anything big I'm missing here?

**Comment by okuoku** [comment]
Where `*.sds` was came from? I think `*.sld` is popular file extension for R7RS libraries definition.

R7RS `cond-expand` proposes `library` feature which is hard-to-implement for us -- we cannot cache the library or, needs some special handling.

How about `include-library-declarations` ?

**Comment by higepon** [comment]
> Where *.sds was came from? I

Sorry. My bad. Updated there.

>  feature which is hard-to-implement for us 

Thanks! I guess library feature is similar to include in a sense that it is ok not to handle it properly IMO.
- Every library with include we should check the included file to see if we invalidate cache.
  - To handle this properly we have to manage a library => included files mapping in the cache system.
  - If we didn't handle this, a library developer has to use mosh --disable-cache when they are developing a library with include. A library user doesn't need to worry about it.
- Every library with library feature we should check the existence of the library to see if we invalidate cache.
  - To handle this properly we have to manage a library => (library ...)s mapping in the cache system.
  - If we didn't handle this. A developer who writes/installs a new library should invalidate cache using mosh --clean-acc.

> How about include-library-declarations ?

Thanks. I think this is feasible. Instead of enclosing it with begin. We just splicing it.

**Comment by higepon** [comment]
btw is cond-expand with ```library feature``` used a lot in major Scheme implementations or libraries?

**Comment by lassik** [comment]
> I think `*.sld` is popular file extension for R7RS libraries definition.

Yes, that's the most popular one. It's used a lot e.g. in snow-fort.org packages.

Chicken and MIT Scheme use some other extension, but IIRC both use a different one.

> R7RS `cond-expand` proposes `library` feature which is hard-to-implement for us -- we cannot cache the library or, needs some special handling.

> btw is cond-expand with `library feature` used a lot in major Scheme implementations or libraries?

It's quite an important feature for portable code. You can e.g. check whether a SRFI is available.

> How about `include-library-declarations` ?

> I think this is feasible. Instead of enclosing it with begin. We just splicing it.

Yes, that's the intent.

**Comment by higepon** [comment]
Thank you lassik! The R7RS style libraries started working (not fully tested though).

**Comment by higepon** [comment]
### Discussion how we oraganize SRFI libraries
#### Expectations
- In R6RS we import them as ```(import (srfi :1))```. I couldn't find it in R6RS, so probably it was a community agreement?
- In R7RS it seems ```(import (srfi-1))``` is used. I can see that in SRFI official repo https://github.com/scheme-requests-for-implementation/srfi-233/blob/main/srfi-233.sld
  - Also it's worth noting that in cond-expand it's written as ```(cond-expand (library srfi 1)``` when checking library availability.

#### How current mosh (R6RS) is treating SRFI
```
lib/srfi/
|-- %3a0
|   `-- cond-expand.sls
|-- %3a0.mosh.sls
|-- %3a1
|   `-- lists.sls
|-- %3a1.mosh.sls
|-- %3a11
|   `-- let-values.sls
|-- %3a11.mosh.sls
|-- %3a13
|   `-- strings.sls
|-- %3a13.mosh.sls
|-- %3a14
|   `-- char-sets.sls
|-- %3a14.mosh.sls
|-- %3a16
|   `-- case-lambda.sls
|-- %3a16.mosh.sls
|-- %3a176
|   `-- version.sls
|-- %3a176.mosh.sls
|-- %3a19
|   |-- time
|   |   |-- compat.ikarus.sls
|   |   |-- compat.larceny.sls
|   |   |-- compat.mosh.sls
|   |   |-- compat.mzscheme.sls
|   |   `-- compat.ypsilon.sls
|   `-- time.sls
|-- %3a19.mosh.sls
|-- %3a2
|   |-- and-let%2a.sls
|   |-- and-let-star.sls
|   `-- and-let.larceny.sls
|-- %3a2.mosh.sls
|-- %3a23
|   `-- error.sls
|-- %3a23.mosh.sls
|-- %3a26
|   `-- cut.sls
|-- %3a26.mosh.sls
|-- %3a27
|   `-- random-bits.sls
|-- %3a27.mosh.sls
|-- %3a31
|   `-- rec.sls
|-- %3a31.mosh.sls
|-- %3a37
|   `-- args-fold.sls
|-- %3a37.mosh.sls
|-- %3a38
|   |-- with-shared-structure.ikarus.sls
|   |-- with-shared-structure.mosh.sls
|   `-- with-shared-structure.ypsilon.sls
|-- %3a38.mosh.sls
|-- %3a39
|   |-- parameters.ikarus.sls
|   |-- parameters.mosh.sls
|   |-- parameters.mzscheme.sls
|   |-- parameters.sls
|   `-- parameters.ypsilon.sls
|-- %3a39.mosh.sls
|-- %3a41
|   |-- streams
|   |   |-- derived.sls
|   |   `-- primitive.sls
|   `-- streams.mosh.sls
|-- %3a41.mosh.sls
|-- %3a42
|   `-- eager-comprehensions.sls
|-- %3a42.mosh.sls
|-- %3a43
|   `-- vectors.sls
|-- %3a43.mosh.sls
|-- %3a48
|   |-- intermediate-format-strings
|   |   |-- compat.ikarus.sls
|   |   |-- compat.larceny.sls
|   |   |-- compat.mosh.sls
|   |   |-- compat.mzscheme.sls
|   |   `-- compat.ypsilon.sls
|   `-- intermediate-format-strings.sls
|-- %3a48.mosh.sls
|-- %3a6
|   |-- basic-string-ports
|   |   |-- compat.ikarus.sls
|   |   |-- compat.larceny.sls
|   |   |-- compat.mosh.sls
|   |   `-- compat.ypsilon.sls
|   |-- basic-string-ports.mzscheme.sls
|   `-- basic-string-ports.sls
|-- %3a6.mosh.sls
|-- %3a61
|   `-- cond.sls
|-- %3a61.mosh.sls
|-- %3a64
|   `-- testing.sls
|-- %3a64.mosh.sls
|-- %3a67
|   `-- compare-procedures.sls
|-- %3a67.mosh.sls
|-- %3a78
|   |-- lightweight-testing
|   |   |-- compat.ikarus.sls
|   |   |-- compat.larceny.sls
|   |   |-- compat.mosh.sls
|   |   |-- compat.mzscheme.sls
|   |   `-- compat.ypsilon.sls
|   `-- lightweight-testing.sls
|-- %3a78.mosh.sls
|-- %3a8
|   `-- receive.sls
|-- %3a8.mosh.sls
|-- %3a9
|   `-- records.sls
|-- %3a9.mosh.sls
|-- %3a98
|   `-- os-environment-variables.sls
|-- %3a98.mosh.sls
|-- %3a99
|   |-- records
|   |   |-- helper.sls
|   |   |-- inspection.larceny.sls
|   |   |-- inspection.sls
|   |   |-- procedural.larceny.sls
|   |   |-- procedural.sls
|   |   |-- syntactic.larceny.sls
|   |   `-- syntactic.sls
|   `-- records.mosh.sls
|-- %3a99.mosh.sls
|-- 13
|   `-- srfi-13.scm
|-- 14
|   `-- srfi-14.scm
|-- 19
|   `-- srfi-19.scm
|-- 26
|   `-- cut.scm
|-- 27
|   |-- random.ss
|   `-- readme
|-- 37
|   `-- srfi-37-reference.scm
|-- 42
|   |-- design.scm
|   |-- ec.scm
|   |-- extension.scm
|   `-- timing.scm
|-- 43
|   `-- vector-lib.scm
|-- 64
|   `-- testing.scm
|-- 67
|   `-- compare.ss
|-- 78
|   `-- check.scm
|-- COPYING
|-- README
|-- compile-all.ikarus.sps
|-- i0.mosh.sls
|-- i19.mosh.sls
|-- i23.mosh.sls
|-- i39.mosh.sls
|-- i6.mosh.sls
|-- i9.mosh.sls
|-- i98.mosh.sls
|-- private
|   |-- OS-id-features.sls
|   |-- include
|   |   |-- compat.ikarus.sls
|   |   |-- compat.larceny.sls
|   |   |-- compat.mosh.sls
|   |   |-- compat.mzscheme.sls
|   |   |-- compat.nmosh.sls
|   |   `-- compat.ypsilon.sls
|   |-- include.sls
|   |-- let-opt.sls
|   |-- make-aliased-libraries.sps
|   |-- platform-features.ikarus.sls
|   |-- platform-features.larceny.sls
|   |-- platform-features.mosh.sls
|   |-- platform-features.mzscheme.sls
|   |-- platform-features.ypsilon.sls
|   `-- registry.sls
`-- sync_mosh.sh

48 directories, 137 files
```

@okuoku IIRC you did most of this work. What do you think is the good way?

#### Some notes
- I would keep both R6RS and R7RS import style for existing ones. For new ones R7RS is totally fine.
- Priority is supporting SRFI we already support in the lib/srfi.
- For new SRFI libraries it is ideal if any SRFI libraries works after we put a SRFI library from their official repo in lib/ directory w/o modification.

**Comment by higepon** [comment]
One official example.
https://github.com/scheme-requests-for-implementation/srfi-227/tree/master/lib/srfi

**Comment by okuoku** [comment]
R6RS names for SRFIs are SRFI-97: https://srfi.schemers.org/srfi-97/srfi-97.html

R7RS names are `(srfi NNN)` for example: https://github.com/scheme-requests-for-implementation/srfi-115/blob/master/contrib/duy-nguyen/srfi/115.sld , https://github.com/scheme-requests-for-implementation/srfi-233/blob/main/srfi/233.sld or https://github.com/scheme-requests-for-implementation/srfi-227/blob/master/lib/srfi/227.sld

> What do you think is the good way?

Handle it specially and convert it.. For example, we should normalize `(srfi :1 lists)`, `(srfi: 1)` and `(srfi 1)` point exact same library.

> One official example.

We should avoid `:` because it's forbidden on Windows.

**Comment by higepon** [comment]
> Handle it specially and convert it.. For example, we should normalize `(srfi :1 lists)`, `(srfi: 1)` and `(srfi 1)` point exact same library.

Thanks for the suggestion. I had the idea too.
- In R7RS mosh, we can easily normalizing it in the library converter.
- In R6RS mosh, it's a bit tricky but I guess it's doable.
- In R6RS | R7RS nmosh ???

**Comment by higepon** [comment]
The steps we need are

- (A) Add lib/srfi/1.scm in addition to the existing lib/srfi/%3a1.scm. Do this for all existing srfi libraries in our repo.
- (B) Implement the conversion logic in mosh and nmosh.
- (C) Test.
- (D) Remove %3a1.scm once (B) and (C) are done?

@okuoku 
- Does this align with your idea?
- Do you think you could do that for nmosh?

**Comment by okuoku** [comment]
> Does this align with your idea?

Yes, but how about keep things mainly in R6RS world, in particular:

1) Allow `library` form also in R7RS reader
2) write `lib/srfi/1.sld` just saying `(define-library (srfi 1) (include-library-declarations "%3a1/lists.sls"))`
3) (Keep existing R6RS libraries)

> Do you think you could do that for nmosh?

I believe I can do so as well. (I don't have any immediate plan to implement R7RS on nmosh anytime soon though; 99% use of nmosh is application embedding and it doesn't play well with R7RS library system that may interact the filesystem directly.)

**Comment by higepon** [comment]
Sounds good to me for the nmosh stuff.
I agree with you that we keep the R7RS one. But I also don't want support (library format).

How about this? It's not ideal but I think it's okay and cleaner.
https://github.com/higepon/mosh/pull/153

**Comment by higepon** [comment]
Also could we confirm which is commonly used (srfi 1) or (srfi-1).

See this.
https://github.com/scheme-requests-for-implementation/srfi-151/blob/master/srfi-151/chibi-test.scm

**Comment by lassik** [comment]
> * In R7RS it seems `(import (srfi-1))` is used.

I don't recommend that. `(import (srfi 1))` (with a space, not a dash) is the most popular way to it in R7RS. It's even endorsed by the standard. (Section 5.6.1. Library Syntax: "Libraries whose first identifier is srfi are reserved for libraries implementing Scheme Requests for Implementation.")

Note that R7RS allows both symbols and numbers (exact non-negative integers) as library name parts. So the `1` in `(srfi 1)` is read as a number, using the normal Scheme reader.

> * In R6RS we import them as `(import (srfi :1))`. I couldn't find it in R6RS, so probably it was a community agreement?

Yes, community agreement.

The reason for the colon (`:`) is that R6RS forbids numbers as library name parts. So the `:` hack turns a number into a symbol.

> * Also it's worth noting that in cond-expand it's written as
>   `(cond-expand (library srfi 1)` when checking library
>   availability.

That syntax is incorrect. It's

    (cond-expand
      ((library (srfi 1))
       <body ...>))

> |-- %3a99.mosh.sls

> * I would keep both R6RS and R7RS import style for existing ones.
>   For new ones R7RS is totally fine.

Most SRFIs are compatible with both R6RS and R7RS. Making them importable from both would be ideal.

> R6RS names for SRFIs are SRFI-97: https://srfi.schemers.org/srfi-97/srfi-97.html

Yes, but see the post-finalization note at the start of the SRFI.

> Handle it specially and convert it.. For example, we should normalize `(srfi :1 lists)`, `(srfi: 1)` and `(srfi 1)` point exact same library.

> We should avoid `:` because it's forbidden on Windows.

Yes.

> The steps we need are
> 
> * (A) Add lib/srfi/1.scm in addition to the existing lib/srfi/%3a1.scm. Do this for all existing srfi libraries in our repo.
> * (B) Implement the conversion logic in mosh and nmosh.
> * (C) Test.
> * (D) Remove %3a1.scm once (B) and (C) are done?

I highly recommending implementing a "library alias" system. I.e. you can define only one of the libraries `(srfi 1)`, `(srfi :1)`, `(srfi :1 lists)`, and say that the other two names are aliases to it.

If you don't have library aliases, the source tree is going to have lots of tiny wrapper files to cover all the names.

Note that the form `(srfi 1 lists)` may be added for R7RS later. There's been some talk about it on the SRFI mailing lists.

The alias system has the nice bonus that you can define a simple name like `(srfi 1)`, and specify the names with colon (`:`) as aliases. That way, there's no need for the `%3a` hack in filenames. (If you do this, and use R6RS `(library ...)` to define the SRFIs, you have to make an extension to R6RS to permit numbers as library name parts like R7RS does.)

> 2. write `lib/srfi/1.sld` just saying `(define-library (srfi 1) (include-library-declarations "%3a1/lists.sls"))`

That won't work since `%3a1/lists.sls` has to contain a complete `(library ...)` form.

Note that `chez-srfi` uses an `(include ...)` mechanism also for R6RS. It's a non-standard extension to R6RS, but it works in many R6RS implementations.

> Also could we confirm which is commonly used (srfi 1) or (srfi-1).

The form `(srfi 1)` (with a space) is almost universally preferred by R7RS users and implementations. (Guile uses some weird custom convention, but there's a bug report about fixing it IIRC.)

The form `(srfi-1)` (with a dash) can be safely forgotten.

**Comment by higepon** [comment]
Thanks for all the comment @lassik.

> `import (srfi 1))` (with a space, not a dash) is the most popular way

OK. Thanks. Will support that.

> That syntax is incorrect. It's

My bad. Thanks for the catch.

> Most SRFIs are compatible with both R6RS and R7RS. Making them importable from both would be ideal.

Ack.

> I highly recommending implementing a "library alias" system

Thanks for the suggestion. I see your point.
We have psyntax layer, R7RS library converter and library caching system. I have to think thorough to make everything works.

**Comment by higepon** [comment]
Huge thanks to both of you.
With https://github.com/higepon/mosh/pull/155 mosh is able to load ```(srfi 151)``` with only 1 change in the original implementation which is renaming ```(srfi-151)``` to ```(srfi 151)```.

This is a huge milestone because [srfi-151.sld](https://github.com/scheme-requests-for-implementation/srfi-151/blob/master/srfi-151/srfi-151.sld) is a really good test for converting R7RS library to R6RS library. 
- It has 2 imports and 4 exports which was not allowed in R6RS.
- It has export(s) follows import(s). In R6RS import follows after export.
- It has cond-expand with feature.
- It has cond-expand with library.
- It has cond-expand with include in it.
- It has 5 include(s).

**Comment by higepon** [comment]
https://github.com/higepon/mosh/pull/157 is prep work for making cache system with include(s).

**Comment by higepon** [comment]
With https://github.com/higepon/mosh/pull/159 the cache system is aware of included files.

**Comment by higepon** [comment]
I'm closing this.

- Mosh can load R7RS style library.
- The library cache system works as expected.
- Existing srfi libraries in the repo can be imported (srfi n).
