### ISSUE TITLE
R7RS MS3: QoL improvement

### ISSUE THREAD

**Issue by higepon** [higepon/mosh#121]
**MS3**: QoL improvement

- Adjust `cond-expand` flags
- Support snow https://snow-fort.org/ ?

Perhaps MS3 need some more clear goal.

**Comment by okuoku** [comment]
> Eventually I want to announce R7RS comformance

How would it be written as in RELNOTE-form? e.g.)

> ### R7RS small support
> `mosh` learned R7RS small libraries and R7RS `define-library` form. Now mosh can load R7RS programs and libraries.
> - Mosh now bundles standard libraries introduced in the R7RS report such as `(scheme base)`, `(scheme repl)`  etc.
> - `*.sld` is now recognized as library extension
> - `(srfi NNN)` can be used to import SRFI vocabulary 
> - R6RS and R7RS can be freely mixed; R6RS libraries and R7RS libraries can be loaded simultaneously  
> 
> To demonstrate R7RS portability, please refer `https://github.com/XXXX/XXXX` that implements XXXXX and it's also compatible with other R7RS implementations such as Chibi-scheme, Gauche and Sagittarius

**Comment by higepon** [comment]
I think your exmple is perfect :)

**Comment by higepon** [comment]
I'm wondering if what else do we need to do to say this is done.

**Comment by okuoku** [comment]
> what else do we need to do to say this is done.

Updating RELNOTE and review its content; so we can ensure what was done in 0.2.8 for user's QoL. (And we can re-use its content for ANN post of c.l.s.) If you feel it's too many for RELNOTE, adding separate README.R7RS.md might be an alternative.

**Comment by okuoku** [comment]
Err, and a benchmark; https://github.com/ecraven/r7rs-benchmarks Personally I think it is nonsense that benchmarking language implementations for a task, it often finds regressions so might be good for QA.

**Comment by higepon** [comment]
Updated the RELNOTE https://github.com/higepon/mosh/pull/206
Please feel free to add more/edit.

**Comment by higepon** [comment]
Now Mosh can run all the r7rs-benchmarks.
I created pull request there and ask them to include our results there.
https://github.com/ecraven/r7rs-benchmarks/pull/64

**Comment by higepon** [comment]
New fixnum https://github.com/higepon/mosh/pull/227

**Comment by higepon** [comment]
RC8 is out.
https://github.com/higepon/mosh/releases/tag/mosh-0.2.8-rc8

**Comment by higepon** [comment]
I think once we confirm RC8 is stable enough. We can release 0.2.8.
@okuoku could you take a look and update https://github.com/higepon/mosh/blob/master/doc/RELNOTE.md for 0.2.8?

**Comment by okuoku** [comment]
Checked https://github.com/higepon/mosh/commit/963275e27dbc27a46f9ade25c0de67496890f18f and content is okay.

> VM:
> VM Compiler error "[internal error] iform-count-size-upto: unknown iform tag:13" was fixed.

Needs indentation. And, maybe we have to mention new `--optimize-level` option in "Features" section?

**Comment by higepon** [comment]
Thanks! Updated it. And reorder some important updates there.

**Comment by higepon** [comment]
Updated https://mosh.monaos.org/ a bit.

**Comment by higepon** [comment]
Releasing 0.2.8 soon.

**Comment by higepon** [comment]
0.2.8 has been released silently.
I'll announce it later today on Twitter and maybe in my blog.

Tweet 1 draft
> After many years @okuoku and I have released Mosh Scheme 0.2.8. Now Mosh runs on M1 mac natively and conforms R7RS. 
https://github.com/higepon/mosh/releases/tag/mosh-0.2.8

Tweet 2 draft
> Also to demonstrate R7RS conformance we wrote MNIST demo written in R7RS.
See https://github.com/higepon/mosh/tree/master/tests/mnist


@okuoku could you double check the release tar.gz, RELNOTE and announcements? 
Thank you for all the help!

**Comment by okuoku** [comment]
"conforms R7RS" => "conforms R7RS small" ? All the others LGTM. 

Many thanks for a new release! As the release includes many significant improvements, maybe we'll have the next release (relatively) sooner than before anyway 🙃

**Comment by higepon** [comment]
Thank you so much!
Announced https://twitter.com/higepon/status/1592091558287147008.
