### ISSUE TITLE
Notes: Mosh 0.2.7 on M1 mac

### ISSUE THREAD

**Issue by higepon** [higepon/mosh#14]
```
 % uname -ar
Darwin higepon-mbp2021.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64
```

Attached my incomplete work for the future readers.
[mosh-0.2.7.zip](https://github.com/higepon/mosh/files/9239043/mosh-0.2.7.zip)

## Random notes
- ```brew install gmp oniguruma```
  - Need to tell make command the include path.
- Need to update Boehm GC to the latest so that it can handle Apple Silicon.
  - Boehm GC directory strcture has changed. We need some minor changes on our Makefile.in. But overall it's trivial.
- Observed some bits related test failures with ```make test```. Some of the errors are coming from multiplication overflow handling in Object::mul. (Need further investigation).

**Comment by higepon** [comment]
### Problem
```
(let ((b (make-bytevector 4 0)))
  (bytevector-sint-set! b 0 -1 'little 4)
  (bytevector-uint-ref b 0 'little 4)) : expected 4294967295 but got -1.
```

### The root cause
The behaviour of ```n1 * n2``` when overflow is undefined. We should use bigger type here. Changing fixedint(=int) to long fixed the problem.
```
    static Object mul(int n1, int n2)
    {
        const fixedint ret = (fixedint)n1 * n2;

        /* Overflow check from Gauche */
        if ((n2 != 0 && ret / n2 != n1) || !Fixnum::canFit(ret)) {
            Return
```

**Comment by higepon** [comment]
```
 (cd tests/r6rs-test-suite/ && MOSH_LOADPATH=/Users/higepon/Downloads/mosh-0.2.7/lib /Users/higepon/Downloads/mosh-0.2.7/mosh  tests/r6rs/run/arithmetic/bitwise.sps)
```

#### The problem
```
(test (bitwise-not #x-FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF)
          340282366920938463463374607431768211454)
```

```
Expression:
 (bitwise-not 1)
Result:
 -2
Expected:
 340282366920938463463374607431768211454
```

**Comment by higepon** [comment]
#### Goal
To be able to release new version of Mosh with M1 changes. We'll have to build [Building the cutting-edge Mosh](Building the cutting-edge Mosh).

#### Install dependencies
```
brew install bison
brew install subversion
brew install autoconf
brew instlal automake
brew install re2c
```
Gauche 0.9.6 and mosh 0.2.7 above.

#### ./gen-git-build.sh   
```
gosh vm.scm compile-file-without-macro runtimes/psyntax-mosh/psyntax.scm > psyntax-mosh-image.scmc
*** ERROR: pair required, but got #f
Stack Trace:
_______________________________________
  0  ((with-module gauche.internal %source-info) obj)
        at "/usr/local/share/gauche-0.9/0.9.6/lib/gauche/vm/debugger.scm":49
  1  (debug-source-info p)
        at "./compiler-vm.scm":2
  2  (source-info sexp)
        at "./compiler-vm.scm":1297
```

The last release of Mosh 0.2.7 was on 2011/6/14. Let's pick the closest Gauche ans see if it works.

**Comment by higepon** [comment]
#### Goal
Run ./gen-git-build.sh  on Linux and bootstrap Mosh so that we can release new mosh.

**Comment by higepon** [comment]
#### TODO
- Build mosh on i386 Ubuntu.
- Bootstrap on i386 Ubuntu
- Update Boehm GC on i386 Ubuntu.
- Update fixedint on i386 Ubuntu.
- Create Dockerfile to bootstrap mosh.
- Create Dockerfile and shell script for i386 Ubuntu.
-

**Comment by higepon** [comment]
#### Goal
Update Boehm GC to the latest using https://github.com/higepon/mosh/tree/master/docker/dev.

**Comment by higepon** [comment]
RC1 of Mosh 0.2.8.
- Tested on i686

**Comment by higepon** [comment]
Now we have https://github.com/higepon/mosh/releases/tag/mosh-0.2.8-rc1

**Comment by okuoku** [comment]
Let me note FreeBSD patches here that'd need to be incorporated future versions: 

- #13 https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=229540 
- J: https://zenn.dev/okuoku/articles/1d9769e3fef7aa632722 https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=248874

**Comment by higepon** [comment]
Thanks for the notes!
https://github.com/higepon/mosh/pull/19 has been created for the cast problem.
For Boehm GC one it would be great if you could verify it still exists in 0.2.8-rc1.

thanks!
