### ISSUE TITLE
mosh 0.2.8RC6 or release

### ISSUE THREAD

**Issue by higepon** [higepon/mosh#164]
Is there anything you want to finish before the release?

- I'd like to support install via package system brew and apt.
  - Reduce gosh dependency.
  - Are we going to use mosh-scheme as official name?

**Comment by okuoku** [comment]
I don't have any functionality item for 0.2.8. In particular, I'm okay to make a release without nmosh R7RS.

For bugfixes, I have: #65 needs to be added to RELNOTE, and #129.

> Are we going to use mosh-scheme as official name?

I'm against the change. Let packagers to handle it.

**Comment by higepon** [comment]
Okay. I'd wait on the bug fixes. 
In the mean time I'll be working on M3.

**Comment by lassik** [comment]
> * Are we going to use mosh-scheme as official name?

That might be a good idea: https://repology.org/projects/?search=mosh

**Comment by higepon** [comment]
I'm not sure how to read it but if you click into it. There' s https://repology.org/project/mosh-scheme/versions.
2 out of 3 packages are maintained by @okuoku. So I'd respect his opinion around this.

**Comment by higepon** [comment]
I'll release 0.2.8RC6 after I update RELNOTE.

**Comment by higepon** [comment]
0.2.8RC6 is out.
Thank you!
