### ISSUE TITLE
r7rs: "Using FAKE implementation of weak-box" warning

### ISSUE THREAD

**Issue by okuoku** [higepon/mosh#193]
Since psyntax-mosh do not provide weak object, non-weak implementation of buffered (= SRFI-6 styled) ports being used.

```
MOSH_LOADPATH=/home/runner/work/mosh/mosh/mosh-latest/lib /home/runner/work/mosh/mosh/mosh-latest/mosh  tests/r7rs/r7rs-tests.scm
WARNING: Using FAKE implementation of weak-box
WARNING: MEMORY LEAK will occur
  (SKIPPED (let () (define-syntax elli-lit-1 (syntax-rules ... (...) ((_ x) '(x ...)))) (test '(100 ...) (elli-lit-1 100))))
```

- https://github.com/higepon/mosh/blob/f0af00d0635a783520e9806e877620589b2afc41/lib/r7b-util/bytevector-buffer.sls
- https://github.com/higepon/mosh/blob/f0af00d0635a783520e9806e877620589b2afc41/lib/r7b-util/string-buffer.sls (IIRC, this one is not used)

IIRC we already have SRFI-6 style string/bytevector output ports on C++ side thus we should be able to remove this fake implementation.

**Comment by higepon** [comment]
Thank you. Will look into this!
