### ISSUE TITLE
Expand top level program with R7RS expander

### ISSUE THREAD

**Issue by higepon** [higepon/mosh#194]
Expand top level program with R7RS expander so that proper cond-expand in top level program works.

**Comment by higepon** [comment]
I need some more details to understand what you meant but here is my thought.
In my understanding we have to support the following in a R7RS scheme program.

- (A) R7RS style import. e.g. Allow multiple import(s).
- (B) Expression: include and include-ci which is aware of where the program is located in the file system.
- (C) Expression: cond-expand which can handle features and library.

None of them are supported in psyntax. (B) and (C) are somewhat supported but not exactly the same.
So I was wondering if we just write small top level program converter (similar to the library converter but smaller).
Same as the library converter, we convert top level program right before we start psyntax expander.

I prefer this way just because
- we are able to reuse the library converter code a lot.
- Clear separation between R7RS and R6RS world (at least in my mind).

>  In other words, do we want to allow cond-expand to choose imported libraries

No I don't think so. Per R7RS "_A Scheme program consists of one or more import decla-
rations followed by a sequence of expressions and definitions._ ". So we don't need to support that case.
IMO it's not necessary.

I think I can come up with a working prototype in a few days. So let's see how it goes.
But I would like your input here.

**Comment by okuoku** [comment]
Two-pass expander need to consider some extreme case. e.g.)

```scheme
(import (rename (scheme base) (include myinclude)))
(define (include x) #t)
(myinclude "hoge.scm") ;; => should we treat this as (include "hoge.scm") ?
(include "hoge.scm") ;; => #t? or treat this as (include "hoge.scm") ?
```

Perhaps we'd need to check other R6RS+R7RS implementations such as Guile3, Sagittarious and Ypsilon.

**Comment by higepon** [comment]
Yeah.  You're right.  The case is tricky and I'm not sure what is expected there.
I think my priority now is "works for most of the use cases".
But we should look into other implementation. They might have smart solution for it.

**Comment by higepon** [comment]
- https://github.com/higepon/mosh/pull/197
