### ISSUE TITLE
r7rs `repl`: `interaction-environment` handling/implementation

### ISSUE THREAD

**Issue by okuoku** [higepon/mosh#199]
Currently, psyntax-mosh do not have `(scheme repl)` implementation. Unlike NMosh, psyntax require some extension to implement it properly.

We could just export psytax' `interaction-environment`, but it do not handle `(library ...)` (and `(define-library ...)`) correctly. I don't recall whether or not R7RS required to implement these, but other R7RS+R6RS implementations such as Ypsilon and Guile3 can handle it. In other words, these implementations allow libraries to be entered on its REPL so they can `(import ...)` later.

**Comment by higepon** [comment]
Thanks for the catch. I exposed interaction-environment in https://github.com/higepon/mosh/pull/200/files. PTAL.

> I don't recall whether or not R7RS required to implement these

I don't think so. Per R7RS small ```(eval ...)``` takes expression or definition. So it doesn't take library-definition in my understanding.

BUT I think it would be helpful if REPL accepts ```(define-library ...)```. Let me take a look if we can do it easily.

**Comment by higepon** [comment]
Now the REPL accepts both library and define-library.

### R6RS
```
mosh> (library (greeting) (export hi) (import (rnrs)) (define hi 'greeting))
#<unspecified>

mosh> hi

Unhandled exception:

 Condition components:
 1. &undefined
 2. &who             who: (hi)
 3. &message         message: "unbound variable"

mosh> (import (greeting))
#<unspecified>

mosh>hi
greeting
```

### R7RS
```
mosh> (define-library (hige) (export a) (import (scheme base)) (define a 3))
#<unspecified>

mosh>(import (hige))
#<unspecified>

mosh>a
3
```

**Comment by higepon** [comment]
https://github.com/higepon/mosh/pull/202
