### ISSUE TITLE
Make head buildable w/o bootstrap

### ISSUE THREAD

**Issue by higepon** [higepon/mosh#211]

**Comment by higepon** [comment]
We may have discussed before but I still think anyone should be able to build mosh head easily except someone who touches bootstrap code such as baselib, psyntax and etc.

Can't we just commit generated code manually or via GitHub Action?

I may explore this sometime soon.

**Comment by okuoku** [comment]
> Can't we just commit generated code manually or via GitHub Action?

It heavily reduces `git grep` usability and bloats the repository so I never think it's a good idea. It'd be far more better make releases frequently and/or just providing binary releases for the purpose.  (Unlike NMosh, psyntax-mosh depends hardcorded installation paths. NMosh provides prefixless mode that uses relative path as default `library-path` and it'd be needed to make binary distribution useful though.)

re: repository bloating, Chez choose dropping bootstrapped files and even rewriting history: https://github.com/cisco/ChezScheme/wiki/Announcements

**Comment by higepon** [comment]
Thanks Chez case is very interesting. 

>  It'd be far more better make releases frequently and/or just providing binary releases for the purpose. 

Yeah. This might be a good solution.
