### ISSUE TITLE
How to get notified CI errors

### ISSUE THREAD

**Issue by higepon** [higepon/mosh#226]
I'm working on Fixnum 32bit => 64bit work and trying to debug CI error in BSD families.
https://github.com/higepon/mosh/actions/runs/3400263605

Is there any way to get more information about the error?
```
2022-11-05T23:19:20.1415030Z ##[error]The process '/bin/bash' failed with exit code 127
2022-11-05T23:19:20.1429940Z ##[error]The process '/bin/bash' failed with exit code 127
```

**Comment by higepon** [comment]
Trying 0.3.0 instead of 0.2.8.
```
vmactions/freebsd-vm@v0.3.0
```

**Comment by okuoku** [comment]
GHA do not give me any error other than triggered by me. Perhaps we would have Slack/Discord or something so we can notice CI error earlier..

**Comment by higepon** [comment]
This particular error has been fixed by updating GHA versions. But I agree.
Any good recommendations for notifications?
I use both Slack and Discord but not very active. I'll check email for sure though.

**Comment by okuoku** [comment]
I use Slack Grid at work but it's prohibitively expensive.. On Discord, I have TONS of notifications everyday so I'm sure I can miss the notification anyways.

... so now I have installed GitHub Mobile to my Pixel phone. I'll receive  mobile notification on assignment and `@` mention; hope that works ! (and sorry for my laziness..)

**Comment by higepon** [comment]
No worries. Thank you for installing the app. It should work.
