### ISSUE TITLE
nmosh doesn't start properly for 0.2.8-rc2

### ISSUE THREAD

**Issue by higepon** [higepon/mosh#23]
Please don't feel pressure to fix this but I'm seeing the following error when starting nmosh.
Do you happen to know what's causing this? Is there any special step needed when bootstraping?

```
% ./nmosh -v
Mosh R6RS scheme interpreter, version 0.2.8 (mosh-0.2.8-rc2 Fri, 19 Aug 2022 15:44:01 +0900) 
 % ./nmosh

 Exception:
    error in raise: unhandled exception has occurred

#<type:condition(#<#<type:record-type-descriptor&assertion #<type:record-type-descriptor&violation #<type:record-type-descriptor&serious #<type:record-type-descriptor&condition #f &conidion-uid #f #f () > &serious-uid #f #f () > &violation-uid #f #f () > &assertion-uid #f #f () >> #<#<type:record-type-descriptor&who #<type:record-type-descriptor&condition #f &conidion-uid #f #f () > &who-uid #f #f ((#f . who)) >close-shared-library > #<#<type:record-type-descriptor&message #<type:record-type-descriptor&condition #f &conidion-uid #f #f () > &message-uid #f #f ((#f . message)) >wrong number of arguments (required 1, got 0) > #<#<type:record-type-descriptor&irritants #<type:record-type-descriptor&condition #f &conidion-uid #f #f () > &irritants-uid #f #f ((#f . irritants)) >(()) >) >

 Stack trace:
    1. throw: <subr>
    2. %ffi-close: <subr>
```

**Comment by higepon** [comment]
Assigning this to okuoku so that he would get notification of this.
You don't have to fix this issue just wanted to know your thought :)

**Comment by okuoku** [comment]
It seems we need `GC_DONT_GC=1` to generate proper bootstrap file for nmosh (J: https://zenn.dev/link/comments/2c78cc5daf9dc1 ) on at least macOS 64bit Intel/ARM. So it seems we do something wrong; stomping GCed object. I'm thinking how do we debug it... -- IIRC we can use stock BoehmGC by disabling `Pair` size optimization so I'll try it.

**Comment by higepon** [comment]
Thanks for looking into it. I recently updated the GC to the latest. I may have done something wrong there.
Also I think we may stop including the GC in our tree and the main reason to have it was for Mona.

**Comment by higepon** [comment]
Some notes for myself about how we're using the GC.

### EXTEND_GC
All Mosh C++ classes have EXTEND_GC macro which is defined as follows.
```cpp
#  define EXTEND_GC : public gc
```

**Comment by higepon** [comment]
Now that I realize we don't run ./configure for Boehm GC so it's possible that we're missing some arch dependent configs in our Makefile. So we should probably stop including Boehm GC.

Btw what did you mean by "stock BoehmGC" there?

**Comment by higepon** [comment]
Just trying to link libgc on Linux using the docker container.
https://github.com/higepon/mosh/pull/25

No luck so far. make test got stuck.

**Comment by higepon** [comment]
Update:
It worked by having the bogus in AnnotetedPair.

**Comment by higepon** [comment]
Next steps
- Confirm if nmosh works
- Confirm if make check passes
- Revert back some commented tests.
- make tar ball
- Confirm it on Mac.

**Comment by higepon** [comment]
Having Boehm GC linked as .so also causes the error.

```
:/workspace/mosh# ./nmosh

 Exception:
    error in raise: unhandled exception has occurred

#<type:condition(#<#<type:record-type-descriptor&assertion #<type:record-type-descriptor&violation #<type:record-type-descriptor&serious #<type:record-type-descriptor&condition #f &conidion-uid #f #f () > &serious-uid #f #f () > &violation-uid #f #f () > &assertion-uid #f #f () >> #<#<type:record-type-descriptor&who #<type:record-type-descriptor&condition #f &conidion-uid #f #f () > &who-uid #f #f ((#f . who)) >close-shared-library > #<#<type:record-type-descriptor&message #<type:record-type-descriptor&condition #f &conidion-uid #f #f () > &message-uid #f #f ((#f . message)) >wrong number of arguments (required 1, got 0) > #<#<type:record-type-descriptor&irritants #<type:record-type-descriptor&condition #f &conidion-uid #f #f () > &irritants-uid #f #f ((#f . irritants)) >(()) >) >

 Stack trace:
    1. throw: <subr>
    2. %ffi-close: <subr>
```

### How to reproduce
Checkout this gc branch and ```./gen-git-build.sh && ./configure && make && make check```

**Comment by okuoku** [comment]
> Btw what did you mean by "stock BoehmGC" there?

https://github.com/okuoku/mosh/commit/844743a1ba6932762ee33820a26992142cd08a79

https://github.com/okuoku/mosh/commit/0892e06f0ce2a6a8c63d9103a0a57fd710be805a

NMosh fork have `--with-system-bdwgc` option for the purpose. But it doesn't fix the problem (as we see in the `AnnotatedPair` workaround.) at least on Intel64 + macOS13.

> It worked by having the bogus in AnnotetedPair.

It doesn't work for me. 

Failure in `gen-git-build.sh` can be reproduced with local build:

1. (Assuming the repository have successful build as `./mosh` with `./configure && make`)
2. `cd boot/runtimes/srfi-mosh`
3. `../../../mosh -5 bootstrap.vanilla-mosh/phase2.scm`

`GC_DONT_GC=1 ../../../mosh -5 bootstrap.vanilla-mosh/phase2.scm` should work successfully, with and without `AnnotatedPair` workaround.

Failed attempts(on Intel64 macOS **13**):

- Inserting `bogus[16]` to `AnnotatedPair`
  - + Disabling `DONT_ADD_BYTE_AT_END` -- it just changed crash location
- `GC_ASSERTIONS` -- didn't trapped anything
- `GC_DEBUG` -- ditto
- `-fsanitize=address` -- just trapped NULL pointer access that means the object recollected prematurely

**Comment by higepon** [comment]
Thanks for the updates!

### Hypotheses
- Default configure of the GC is not enough for our use case both for Intel and M1 mac.
- There's a bug in the phase2.scm script which happens to work properly sometimes?
- We are missing one or more GC_ROOT which should be scanned?

**Comment by higepon** [comment]
https://github.com/ivmai/bdwgc/blob/master/doc/debugging.md

**Comment by higepon** [comment]
Reverting my recent changes on NumberReader.y didn't fix the issue.

**Comment by higepon** [comment]
I will work on https://github.com/ivmai/bdwgc/blob/master/doc/debugging.md#prematurely-reclaimed-objects

**Comment by higepon** [comment]
This is has been fixed as side effect of https://github.com/higepon/mosh/issues/26.
Bootstraping on Ubuntu aarch64 produced proper nmosh.

You can confirm the fix at https://github.com/higepon/mosh/releases/tag/mosh-0.2.8-rc3.

**Comment by okuoku** [comment]
👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍

Confirmed fix on Ubuntu2204 amd64.
