### ISSUE TITLE
Write syntax of ports

### ISSUE THREAD

**Issue by lassik** [higepon/mosh#232]
```
mosh> (current-output-port)
<transcoded-textual-output-port standard-out-port>
```

The write syntax uses only `<`. It does not use `#<`. Is this intentional?

Mosh uses `#<` to write other types of unreadable objects, e.g. `#<subr +>` and `#<eof-object>`.

**Comment by higepon** [comment]
Thank you for the catch. It's not intentional. For consistency it should start with #.
Here is the fix https://github.com/higepon/mosh/pull/233.

Thank you!

**Comment by lassik** [comment]
Great, thanks!
