### ISSUE TITLE
akku

### ISSUE THREAD

**Issue by higepon** [higepon/mosh#235]
Install akku on Ubuntu.

```
apt install libcurl4-openssl-dev
apt install guile-3.0-dev
```

**Comment by higepon** [comment]
Thank you lassik!
I tried some packages of akku with Mosh 0.2.8 and it worked w/o any problems.
I'm asking the person for help to see if we can increase coverage https://gitlab.com/akkuscm/akku/-/issues/66.

**Comment by lassik** [comment]
Excellent!
