### ISSUE TITLE
Exposing the supported SRFIs trough (features)

### ISSUE THREAD

**Issue by Retropikzel** [higepon/mosh#262]
These Scheme implementations have supported SRFIs listed on the (features) list.

- Gauche
- Guile
- Kawa
- Stklos
- Gambit
- Chicken

Would it be possible to expose them in Mosh too?

It would help when writing portable code that might depend on SRFI, but fall back on (mayber slower) portable implementation.

**Comment by lassik** [comment]
At https://github.com/ashinn/chibi-scheme/issues/995 I recommended the R7RS idiom `(cond-expand ((library (srfi 123)) ...))` instead.

But R6RS does not have `cond-expand` in the standard at all.

**Comment by Retropikzel** [comment]
I did not respond to https://github.com/ashinn/chibi-scheme/issues/995 as it's closed but I'll answer here that form "(library..." works fine, I should have read the R7RS more closely instead of assuming from the behavior of the implementatins I listed.
