### ISSUE TITLE
Add GitHub Actions to make a release

### ISSUE THREAD

**Issue by higepon** [higepon/mosh#37]
Hopefully we can release 0.2.8 RC4 with this.
@okuoku had an idea to do this.

**Comment by okuoku** [comment]
I think we can copy&paste most from Groonga https://github.com/groonga/groonga/blob/master/.github/workflows/package.yml , it uses https://github.com/softprops/action-gh-release to create GH release from GHA.

**Comment by higepon** [comment]
Thanks for the pointer. Let me work on it!

**Comment by higepon** [comment]
I was able to make it work in https://github.com/higepon/mosh/pull/39. Now NaturalDocs and r6rs doc are cached.
