### ISSUE TITLE
R7RS support?

### ISSUE THREAD

**Issue by higepon** [higepon/mosh#49]
A discussion thread for R7RS.
I'm not very sure if I'd work on this yet.

Just wanted to understand
- Desire to support R7RS?
- Is it going to be 1 month? 6 month? or more than year work?
- Write mainly in Scheme? A lot of C++ work?
- Any research/prep done already?
- Any other better option than work on R7RS?

### Links
- [r7rs-work/R7RSSmallErrata.md at master · johnwcowan/r7rs-work](https://github.com/johnwcowan/r7rs-work/blob/master/R7RSSmallErrata.md)
- https://standards.scheme.org/unofficial/errata-corrected-r7rs.pdf (R7RS Small, final)
- https://codeberg.org/scheme/r7rs/issues (R7RS large, work in progress, will take several more years until final)

**Comment by okuoku** [comment]
I worked it for a while ago but I'm still negative to make us fully conformant to R7RS. Even on 2022,

- Not yet get good traction for library ecosystem. Except SRFI reference implementations, it's far from saying it had plenty external libraries.
- Library format is poorly designed. Most of R7RS libraries are designed for 2 files `.sld` + `.scm` with C-preprocessor style `#include`-ing. It require sort-of virtual filesystem for embedded use and dedicated dependency tracking https://github.com/okuoku/mosh/commit/3f7f79e12bc79330c67a2d5f0258acb48733b578 .
- Semantics discussion still not being settled yet. e.g.) https://groups.google.com/g/scheme-reports-wg2/c/EAF0ZsFeqmU/m/4kqNBKS8AgAJ

My R7RS work on nmosh was resulted to [r7rs-bridge](https://github.com/okuoku/r7rs-bridge) and [yuni](https://github.com/okuoku/yuni); these became starting point of [R7RS implementation in Guile](https://git.savannah.gnu.org/cgit/guile.git/tree/module/scheme/base.scm?id=0aa1a9976fc3c6af4d1087e59d728cb8fe7d369a#n18). Thusly, I think it's not too far from supporting R7RS-small on (n)mosh. Sagittarius is another "R6RS then R7RS" implementation and its implementation is summarised in his paper( http://www.schemeworkshop.org/2014/papers/Kato2014.pdf ).

Heavy-lifting part:

- We have to modify psyntax to comply R7RS program/module format. On nmosh, I wrote R7RS->R6RS lowerer and [Chez mentioned the same approach](https://github.com/cisco/ChezScheme/pull/396#issuecomment-507798669) .
- Several performance constructs are not compatible with R6RS so we have to write dedicated implementations. e.g.) `map` is SRFI-1, `write` is SRFI-38 etc.

Moderate ones:

- We have to adopt R7RS compliant reader. `|symbols with space|`, `#u8()` bytevector https://github.com/okuoku/mosh/commit/09892d202c2e9862516925bdc352c24dd53f5a86 and long-form constants https://github.com/okuoku/mosh/commit/6b246d1b47f50325c2db0c903cf1a2299610f5f1 .
-  Currently, psyntax-mosh lacks file based dependency tracking thus we need extend it.

So if we intend just to say "mosh now can load R7RS libraries as well", the work amount should be 1 to several months. In case you have some **particular** R7RS libraries/programs that needed to be loaded to psyntax-mosh, I think I can backport my nmosh R7RS work to implement R7RS-small partially.

But, I don't think R7RS support is high priority item at this moment. Currently Mosh is way too hard to build and install to evaluate and I think improvement on it is top-priority. e.g.) Consider dropping Gauche from bootstrap process.

**Comment by higepon** [comment]
Thank you for the details!
I'll spend at least a few more days to have better understanding.

For now I'm thinking of what best we can do within 1 to several months.

> Currently Mosh is way too hard to build and install to evaluate and I think improvement on it is top-priority. 

Can't agree more. I think we can do this in parallel with the possible R7RS(?) work.
Good starting point would be support (or support again) Mosh in homebrew, apt and whatever major package systems.
Now we have stable CI and docker. It should be easy once we release 0.2.8.

**Comment by lassik** [comment]
> Most of R7RS libraries are designed for 2 files `.sld` + `.scm`

That's a popular convention, but using only a `.sld` file works too.

> with C-preprocessor style `#include`-ing.

I.e. `(cond-expand ...)` and `(include "foo.scm")`. This is absolutely necessary for portable code.

**Comment by lassik** [comment]
Nb. Chibi-Scheme implements R7RS Small Edition and not much more. So checking "how does Chibi do it?" is usually a reasonable approximation of what R7RS says.

**Comment by okuoku** [comment]
Pure research things aside, I think we can split R7RS works into 3 milestones:

**MS1**: Pass chibi-scheme R7RS test suite https://github.com/ashinn/chibi-scheme/blob/master/tests/r7rs-tests.scm

- Backport nmosh R7RS standard libraries
- Implement Reader extensions; nmosh did the most and only remaining is `|symbol|` IIRC
- Fix bugs found by chibi-scheme test suite

When MS1 completed, we can run R7RS programs that uses Scheme programs that uses `(scheme base)`. 

**MS2**: Implement R7RS library handling

- Implement R7RS library constructs; `define-library` `include` `include-ci` `cond-expand`
- Implement ACC for R7RS libraries

When MS2 completed, we can import R7RS libraries such as https://github.com/scheme-requests-for-implementation/srfi-233 directly.

**MS3**: QoL improvement

- Adjust `cond-expand` flags
- Support snow https://snow-fort.org/ ?

Perhaps MS3 need some more clear goal. 

JFYI: Akku https://akkuscm.org/ implements R7RS->R6RS library converter and its runtime library https://gitlab.com/akkuscm/akku-r7rs is also based on nmosh... we might have to care to avoid conflicts.

**Comment by lassik** [comment]
Akku's author is a good collaborator on all matters related to portable Scheme. If you need some R6<->R7 advice, or need to change something in Akku so it works better with Mosh, just email him.

**Comment by higepon** [comment]
Did [R7RS Quick Research · Issue #54 · higepon/mosh](https://github.com/higepon/mosh/issues/54).

> Pure research things aside, I think we can split R7RS works into 3 milestones:

Thanks for the milestones. MS1 looks a good starting point though I don't understand how we do it in detail.
I think I'll have to figure out how mosh reads R7RS style library syntax to run the chibi-scheme R7RS test suite.

I believe this is talking about it.

> Heavy-lifting part:
>
>    We have to modify psyntax to comply R7RS program/module format. On nmosh, I wrote R7RS->R6RS lowerer and https://github.com/cisco/ChezScheme/pull/396#issuecomment-507798669 .

**Comment by higepon** [comment]
My first R7RS PR :)
https://github.com/higepon/mosh/pull/63

**Comment by higepon** [comment]
> * Backport nmosh R7RS standard libraries

@okuoku Could I have a pointer for this nmosh implementation?

Did you mean we add this to mosh's baselib.scm or somewhere and expose them as ```(scheme xxx)``` using psyntax expander?

**Comment by okuoku** [comment]
> Could I have a pointer for this nmosh implementation?

nmosh implementation is in yuni.

https://github.com/okuoku/yuni/tree/master/lib-r6rs
https://github.com/okuoku/yuni/tree/master/lib-compat/nmosh-r7b-util
https://github.com/okuoku/yuni/tree/master/lib-compat/nmosh-r7b

These implementations still need to some nmosh extension which is not landed in this repository (yet).

- `(r7b-impl *)` are R7RS libraries. e.g. `(r7b-impl base)` is for `(scheme base)`. https://github.com/okuoku/r7rs-bridge/tree/master/lib-r6rs/scheme will perform this library rename (but it's not maintained for a while).
- `(r7b-util *)` are utility libraries for `r7b-impl`.
- `(nmosh-r7b-util *)` are for implementation-dependent parts of r7b. It's needs to be renamed e.g. `(nmosh-r7b-util eval)` => `(r7b-util eval)`
- `(nmosh-r7b *)` is same for `nmosh-r7b-util` but replacement rule is `nmosh-r7b` => `r7b-compat`.

**Comment by higepon** [comment]
Thank you! Let me figure out what's my good next step.

**Comment by higepon** [comment]
Summary for further discussion.
### How we export R7RS small library
#### Background
In https://github.com/higepon/mosh/pull/63 we added R7RS reader support and now mosh can read [r7rs-tests.scm](https://github.com/ashinn/chibi-scheme/blob/master/tests/r7rs-tests.scm). As a next step we'd like to be able to resolve r7rs scheme libraries such as ```(scheme base)```.

#### Options to implement missing procedures
- (A) Implement in C++. ```cons``` as [consEx](https://github.com/higepon/mosh/blob/master/src/ListProcedures.cpp#L154). We can call this **backend**.
  - We can export this type of procedures to R6RS/R7RS world in [mosh/psyntax-buildscript-mosh.ss](https://github.com/higepon/mosh/blob/master/boot/runtimes/psyntax-mosh/psyntax-buildscript-mosh.ss#L317)
- (B) Implement in binary embedded scheme procedure.
  - Procedures in [mosh/boot/baselib](https://github.com/higepon/mosh/tree/master/boot/baselib) are pre-compiled and embedded in mosh binary.  We can call this **backend**.
  - We can export this type of procedures to R6RS/R7RS world in [mosh/psyntax-buildscript-mosh.ss](https://github.com/higepon/mosh/blob/master/boot/runtimes/psyntax-mosh/psyntax-buildscript-mosh.ss#L317)
- (C) Implement in R6RS/R7RS library. We can call this **frontend**.
  - Same as other libraries written in Scheme.
  - Some of this type of procedures may depend on (A) or (B) for implementation details.

#### Options to export R7RS procedures as libraries
- (X) Export them in psyntax world
  - Say we want to have ```(scheme r5rs)``` implemented and all procedures required are implemented in (A) or (B).  We can export them in [psyntax-buildscript-mosh.ss](https://github.com/higepon/mosh/blob/master/boot/runtimes/psyntax-mosh/psyntax-buildscript-mosh.ss#L275)
  - This library resolution info is pre-compiled and embedded to mosh binary. Same as ```(rnrs)```.
  - Pros
    - Loading time is faster.
  - Cons
    - All procedures required should be implemented in (A) or (B).
    - nmosh support?
- (Y) Export them in R6RS/R7RS world
  - Example [srfi 176](https://github.com/higepon/mosh/blob/master/lib/srfi/%253a176/version.sls).
  - Note that even if this is frontend work, it may require backend work and we need to export the work as ```(mosh r7rs implementation)```.
  - Pros
    - Easy to understand and organize.
    - nmosh support is easier.
  - Cons
     - Probably slower loading time on runtime.

#### Discussion notes
- I personally want to go with (Y) and never want to have mixture of (X) and (Y). Thoughts?
- Am I missing any other important factors?

####

**Comment by higepon** [comment]
> For debuggability/performance POV, there might be `(A)` `(B)` `(C)` procedures co-existed. For example, R7RS `member` is SRFI-1 so we need separate implementation. Since `member` is frequently-used loop procedure, we might want to have _both_ [R6RS `member`](https://github.com/higepon/mosh/blob/8141ca9c81bcd8c254095500399a610ede30a717/src/ListProcedures.cpp#L118-L132) and R7RS `member` in native implementation so it falls into `(A)` category.

Yes. This makes sense.

Re: (X), (Y) and allow (X) + (Y). which one would you recommend?
I think your have more experienced and we'll likely use at least some of your yuni work. So I wanted to have your input here :)

**Comment by higepon** [comment]
Sounds good. Let me work on (Y) then.

**Comment by higepon** [comment]
Update. Now we can run some part of ```tests/r7rs/r7rs-tests.scm```
You can see some results and Segmentation fault :)
I'll fix the Segmentation fault then fix them from top to bottom. @okuoku please feel free to take some of them if you're ready. Probably from bottom to top.

```
%%%% Starting test R7RS
FAIL ,((promise? (delay (+ 2 2))) #t)
FAIL ,((promise? (make-promise (+ 2 2))) #t)
FAIL ,((let ((x (delay (+ 2 2)))) (force x) (promise? x)) #t)
FAIL ,((let ((x (make-promise (+ 2 2)))) (force x) (promise? x)) #t)
FAIL ,((force (make-promise (+ 2 2))) 4)
FAIL ,((force (make-promise (make-promise (+ 2 2)))) 4)
FAIL ,((underscore foo) '_)
FAIL ,((finite? 3.0+inf.0i) #f)
FAIL ,((infinite? 3.0+inf.0i) #t)
FAIL ,((nan? 1+2i) #f)
FAIL ,((= 9.007199254740992e15 9007199254740993) #f)
FAIL ,#f
FAIL ,((atan -0.0 1.0) -0.0)
FAIL ,((atan 1.0 0.0) 1.5707963267949)
FAIL ,((atan 1.0 -1.0) 2.35619449019234)
FAIL ,((atan 0.0 -1.0) 3.14159265358979)
FAIL ,((atan -1.0 0.0) -1.5707963267949)
FAIL ,((atan -1.0 1.0) -0.785398163397448)
FAIL ,((sqrt -1.0-0.0i) 0.0+1.0i)
FAIL ,((string->number 1 2) #f)
FAIL ,((member B '(a b c) string-ci=?) '(b c))
FAIL ,((assoc 2.0 '((1 1) (2 4) (3 9)) =) '(2 4))
FAIL ,((list-copy foo) foo)
FAIL ,((list-copy '(3 . 4)) '(3 . 4))
FAIL ,((list-copy '(6 7 8 . 9)) '(6 7 8 . 9))
FAIL ,((digit-value ٤) 4)
FAIL ,((digit-value ૦) 0)
FAIL ,((string->list abc 0) '(a b c))
FAIL ,((string->list abc 1) '(b c))
FAIL ,((string->list abc 1 3) '(b c))
FAIL ,((string-copy  0) )
FAIL ,((string-copy  0 0) )
FAIL ,((string-copy abc 0) abc)
FAIL ,((string-copy abc 1) bc)
FAIL ,((string-copy abc 1 2) b)
FAIL ,((string-copy abc 1 3) bc)
FAIL ,((let ((str (make-string 5 x))) (string-fill! str -) str) -----)
FAIL ,((let ((str (make-string 5 x))) (string-fill! str - 2) str) xx---)
FAIL ,((let ((str (make-string 5 x))) (string-fill! str - 2 3) str) xx-xx)
FAIL ,((vector->list '#(dah dah didah) 1) '(dah didah))
FAIL ,((vector->list '#(dah dah didah) 1 2) '(dah))
FAIL ,((string->vector ABC 1) #(B C))
FAIL ,((string->vector ABC 1 2) #(B))
FAIL ,((vector->string #(1 2 3) 1) 23)
FAIL ,((vector->string #(1 2 3) 1 2) 2)
FAIL ,((vector-copy #(a b c) 1) #(b c))
FAIL ,((vector-copy #(a b c) 1 2) #(b))
FAIL ,((let ((vec (vector 1 2 3 4 5))) (vector-fill! vec 'smash 2 4) vec) #(1 2 smash smash 5))
FAIL ,((let ((vec (vector 1 2 3 4 5))) (vector-fill! vec 'x 2) vec) #(1 2 x x x))
FAIL ,((let ((vec (vector 1 2 3 4 5))) (vector-fill! vec 'x 2 3) vec) #(1 2 x 4 5))
FAIL ,((let ((vec (vector 1 2 3 4 5))) (vector-copy! vec 1 #(a b c d e) 0 2) vec) #(1 a b 4 5))
FAIL ,((let ((vec (vector 1 2 3 4 5))) (vector-copy! vec 0 #(a b c d e)) vec) #(a b c d e))
FAIL ,((let ((vec (vector 1 2 3 4 5))) (vector-copy! vec 0 #(a b c d e) 2) vec) #(c d e 4 5))
FAIL ,((let ((vec (vector 1 2 3 4 5))) (vector-copy! vec 2 #(a b c d e) 0 3) vec) #(1 2 a b c))
FAIL ,((let ((vec (vector 1 2 3 4 5))) (vector-copy! vec 2 #(a b c d e) 2 3) vec) #(1 2 c 4 5))
FAIL ,((let ((vec (vector 1 2 3 4 5))) (vector-copy! vec 1 vec 0 2) vec) #(1 1 2 4 5))
FAIL ,((let ((vec (vector 1 2 3 4 5))) (vector-copy! vec 3 vec 0 2) vec) #(1 2 3 1 2))
FAIL ,((bytevector-length (bytevector 0 1 2)) 3)
FAIL ,((bytevector-u8-ref (bytevector 0 1 2) 0) 0)
FAIL ,((bytevector-u8-ref (bytevector 0 1 2) 1) 1)
FAIL ,((bytevector-u8-ref (bytevector 0 1 2) 2) 2)
FAIL ,((let ((bv (bytevector 0 1 2))) (bytevector-u8-set! bv 1 255) bv) #vu8(0 255 2))
FAIL ,((bytevector-copy #vu8(0 1 2) 1) #vu8(1 2))
FAIL ,((bytevector-copy #vu8(0 1 2) 1 2) #vu8(1))
FAIL ,((let ((bv (bytevector 1 2 3 4 5))) (bytevector-copy! bv 1 #vu8(6 7 8 9 10) 0 2) bv) #vu8(1 6 7 4 5))
FAIL ,((let ((bv (bytevector 1 2 3 4 5))) (bytevector-copy! bv 0 #vu8(6 7 8 9 10)) bv) #vu8(6 7 8 9 10))
FAIL ,((let ((bv (bytevector 1 2 3 4 5))) (bytevector-copy! bv 0 #vu8(6 7 8 9 10) 2) bv) #vu8(8 9 10 4 5))
FAIL ,((let ((bv (bytevector 1 2 3 4 5))) (bytevector-copy! bv 2 #vu8(6 7 8 9 10) 0 3) bv) #vu8(1 2 6 7 8))
FAIL ,((let ((bv (bytevector 1 2 3 4 5))) (bytevector-copy! bv 2 #vu8(6 7 8 9 10) 2 3) bv) #vu8(1 2 8 4 5))
FAIL ,((let ((bv (bytevector 1 2 3 4 5))) (bytevector-copy! bv 1 bv 0 2) bv) #vu8(1 1 2 4 5))
FAIL ,((let ((bv (bytevector 1 2 3 4 5))) (bytevector-copy! bv 3 bv 0 2) bv) #vu8(1 2 3 1 2))
FAIL ,((bytevector-append #vu8()) #vu8())
FAIL ,((bytevector-append #vu8() #vu8()) #vu8())
FAIL ,((bytevector-append #vu8() #vu8(0 1 2)) #vu8(0 1 2))
FAIL ,((bytevector-append #vu8(0 1 2) #vu8()) #vu8(0 1 2))
FAIL ,((bytevector-append #vu8(0 1 2) #vu8(3 4)) #vu8(0 1 2 3 4))
FAIL ,((bytevector-append #vu8(0 1 2) #vu8(3 4) #vu8(5)) #vu8(0 1 2 3 4 5))
FAIL ,((utf8->string #vu8(0 65 66 67) 1) ABC)
FAIL ,((utf8->string #vu8(0 65 66 67 0) 1 4) ABC)
FAIL ,((utf8->string #vu8(0 206 187 0) 1 3) λ)
FAIL ,((string->utf8 ABC 1) #vu8(66 67))
FAIL ,((string->utf8 ABC 1 2) #vu8(66))
FAIL
FAIL ,((map + '(1 2 3) '(4 5 6 7)) '(5 7 9))
FAIL ,((let ((ls1 (list 10 100 1000)) (ls2 (list 1 2 3 4 5 6))) (set-cdr! (cddr ls1) ls1) (map * ls1 ls2)) '(10 200 3000 40 500 6000))
FAIL ,((string-map (lambda (c k) (if (eqv? k u) (char-upcase c) (char-downcase c))) studlycaps xxx ululululul) StUdLyCaPs)
FAIL ,((vector-map + '#(1 2 3) '#(4 5 6 7)) #(5 7 9))
FAIL ,((let ((ls1 (list 10 100 1000)) (ls2 (list 1 2 3 4 5 6)) (count 0)) (set-cdr! (cddr ls1) ls1) (for-each (lambda (x y) (set! count (+ count (* x y)))) ls2 ls1) count) 9750)
FAIL ,((file-error? (guard (exn (else exn)) (open-input-file  no such file ))) #t)
Segmentation fault
```

**Comment by higepon** [comment]
Record as of 9/18/2022. 
```
# of expected passes      1081
# of unexpected failures  125
```

**Comment by higepon** [comment]
Record as of 9/19/2022.
mosh.git/tests/r7rs/r7rs-tests.scm
```
# of expected passes      1166
# of unexpected failures  39
```

Remaining major failures

- [ ] promise implementation
- [ ] underscore in syntax-rules
- [ ] ```(= 9007199254740992.0 9007199254740993)```
- [ ] atan
- [ ] sqrt
- [ ] (string->number "1 2")
- [ ] (assoc 2.0 '((1 1) (2 4) (3 9)) =)
- [ ] digit-value
- [ ] vector-copy!

**Comment by higepon** [comment]
With https://github.com/higepon/mosh/pull/117, now r7rs-tests.scm is enabled in make check. 

```
[  PASSED  ] 1174 passed, 42 skipped.
```

There are still 42 skip(s) and I categorized them into 3 buckets. Please let me know what you think.
Also I'd appreciate it if you could help and fix some of them.


To @okuoku 
- Do you have R7RS promise implementation we can use?
- Do you have atan implementation we can use?
- Any failures you want me prioritize to fix?


## P0: Must fix
```
  (SKIPPED (test #(1 1 2 4 5) (let ((vec (vector 1 2 3 4 5))) (vector-copy! vec 1 vec 0 2) vec)))
  (SKIPPED (test-error (apply +)))
  (SKIPPED (test 'abc (read (open-input-string "#!fold-case ABC"))))
  (SKIPPED (test 'ABC (read (open-input-string "#!fold-case #!no-fold-case ABC"))))
  (SKIPPED (test '(a . b) (read (open-input-string "(a . b #;c)"))))
  (SKIPPED (test-read-error "(#;a . b)"))
  (SKIPPED (test-read-error "(a . #;b)"))
  (SKIPPED (test-read-error "(#;x #;y . z)"))
```

## P1: Want to fix
```
  (SKIPPED (test #t (promise? (delay (+ 2 2)))))
  (SKIPPED (test #t (promise? (make-promise (+ 2 2)))))
  (SKIPPED (test #t (let ((x (delay (+ 2 2)))) (force x) (promise? x))))
  (SKIPPED (test #t (let ((x (make-promise (+ 2 2)))) (force x) (promise? x))))
  (SKIPPED (test 4 (force (make-promise (+ 2 2)))))
  (SKIPPED (test 4 (force (make-promise (make-promise (+ 2 2))))))
  (SKIPPED (test-write-syntax "|\"|" '|\"|))
  (SKIPPED (test '_ (underscore foo)))
  (SKIPPED (test '(2 0 many) (list (count-to-2 a b) (count-to-2) (count-to-2 a b c d))))
  (SKIPPED (test '(2 0 fail fail) (list (count-to-2_ _ _) (count-to-2_) (count-to-2_ a b) (count-to-2_ a b c d))))
  (SKIPPED (let () (define x 1) (let-syntax () (define x 2) #f) (test 1 x)))
  (SKIPPED (let () (define-syntax elli-lit-1 (syntax-rules ... (...) ((_ x) '(x ...)))) (test '(100 ...) (elli-lit-1 100))))
```

## P2: Would be great to fix.
```
  (SKIPPED (test-precision "-1.7976931348623157e+308" "-inf.0"))
  (SKIPPED (test-precision "1.976262583364986e-323" "1.97626258336499e-323" "2.0e-323" "0.0"))
  (SKIPPED (test-precision "1.7976931348623157e+308" "+inf.0"))
  (SKIPPED (test 0.0 (atan 0.0 1.0)))
  (SKIPPED (test -0.0 (atan -0.0 1.0)))
  (SKIPPED (test 0.785398163397448 (atan 1.0 1.0)))
  (SKIPPED (test 1.5707963267949 (atan 1.0 0.0)))
  (SKIPPED (test 2.35619449019234 (atan 1.0 -1.0)))
  (SKIPPED (test 3.14159265358979 (atan 0.0 -1.0)))
  (SKIPPED (test -3.14159265358979 (atan -0.0 -1.0)))
  (SKIPPED (test -2.35619449019234 (atan -1.0 -1.0)))
  (SKIPPED (test -1.5707963267949 (atan -1.0 0.0)))
  (SKIPPED (test -0.785398163397448 (atan -1.0 1.0)))
  (SKIPPED (test 0.0+1.0i (sqrt -1.0-0.0i)))
  (SKIPPED (test #f (string->number "1 2")))
  (SKIPPED (test #t (read-error? (guard (exn (else exn)) (read (open-input-string "\""))))))
  (SKIPPED (test 'error (let ((in (open-input-string "abc"))) (close-input-port in) (guard (exn (else 'error)) (read-char in)))))
  (SKIPPED (test #t (char-ready? (open-input-string "42"))))
  (SKIPPED (test "((1 2 3) (1 2 3))" (let ((out (open-output-string)) (x (list 1 2 3))) (write (list x x) out) (get-output-string out))))
  (SKIPPED (test "line 1\n\nline 3\n" (read (open-input-string "\"line 1\\ \t \n \t \n\nline 3\n\""))))
```

**Comment by higepon** [comment]
Split this work into 3 pieces as okuoku suggested.
I think we're close to finish MS1.

- https://github.com/higepon/mosh/issues/119
- https://github.com/higepon/mosh/issues/120
- https://github.com/higepon/mosh/issues/121

**Comment by lassik** [comment]
Excellent work!

**Comment by higepon** [comment]
Thank you lassik for all the help!
