### ISSUE TITLE
Cygwin Build in GitHub Actions

### ISSUE THREAD

**Issue by higepon** [higepon/mosh#51]

**Comment by higepon** [comment]
It would be great if we could set up this.

**Comment by higepon** [comment]
I don't have Windows or cygwin running on my local. Maybe we can find someone on Docker Hub?

**Comment by okuoku** [comment]
Okay, I'll implement/maintain the port, as a daily user (seriously)

**Comment by higepon** [comment]
Cool. Thanks for taking it!

**Comment by okuoku** [comment]
Memo: I gave-up Windows runner for GHA before https://github.com/ashinn/chibi-scheme/pull/654 but if we see improvement here, we would propose same for chibi-scheme.
