### ISSUE TITLE
R7RS Quick Research

### ISSUE THREAD

**Issue by higepon** [higepon/mosh#54]
### Goal
- Understand the size of the spec.
  - => R7RS Small is actually small.
- Understand the state of the spec.
  - => R7RS Small is final.
- Understand what Scheme projects implement it and how much.
  - Gauche
    - [[Scheme-reports] Gauche joins the ranks of the R7RS implementations](http://www.scheme-reports.org/mail/scheme-reports/msg03570.html)
    - [R7RS integration (Gauche Users’ Reference)](https://practical-scheme.net/gauche/man/gauche-refe/R7RS-integration.html)
  - Ypsilon
    - R7RS small + a few R7RS libraries. [ypsilon/README.md](https://github.com/fujita-y/ypsilon/blob/1851908c7e943962d9c52b520bc9889fc8e7678f/README.md#L22)
- What would we get by supporting it.
  - Mosh doesn't look old :)
  - Ability run some R7RS code in the wild.

**Comment by lassik** [comment]
* https://standards.scheme.org/unofficial/errata-corrected-r7rs.pdf (R7RS Small, final)
* https://codeberg.org/scheme/r7rs/issues (R7RS large, work in progress, will take several more years until final)

**Comment by higepon** [comment]
Thanks for the links.
