### ISSUE TITLE
Suspicious CI artifact contents

### ISSUE THREAD

**Issue by okuoku** [higepon/mosh#86]
Uploaded sizes of bootstrapped source archive are look very different:

![image](https://user-images.githubusercontent.com/100813/190856307-fa047a5b-9aed-40d8-bdb2-a75a3fe33032.png)

(This can be accessed through "Actions" tab → Select any completed job)

Perhaps we'd better to compare these and check if we included anything not intended to be included in the archive.

**Comment by higepon** [comment]
Will do! Thanks for the catch.

**Comment by higepon** [comment]
They have .o files.
```
│   ├── Transcoder.cpp
│   ├── Transcoder.h
│   ├── Transcoder.o
│   ├── UTF16Codec.cpp
│   ├── UTF16Codec.h
│   ├── UTF16Codec.o
│   ├── UTF32Codec.cpp
│   ├── UTF32Codec.h
│   ├── UTF32Codec.o
│   ├── UTF8Codec.cpp
│   ├── UTF8Codec.h
│   ├── UTF8Codec.o
│   ├── UtilityProcedures.cpp
│   ├── UtilityProcedures.h
│   ├── UtilityProcedures.o
│   ├── VM-Profiler.cpp
│   ├── VM-Profiler.o
│   ├── VM-Run.cpp
│   ├── VM-Run.h
│   ├── VM-Run.o
│   ├── VM-inl.h
│   ├── VM.cpp
│   ├── VM.h
│   ├── VM.o
```

**Comment by higepon** [comment]
It seems having src and extlibs in EXTRA_DIST causing this? 
@okuoku do you know the right way to remove *.o files here?

**Comment by okuoku** [comment]
It seems we need to update GTest. I'll take a look.
