### ISSUE TITLE
bytevector-copy!

### ISSUE THREAD

**Issue by lassik** [higepon/mosh#88]
Beware of the infamous `bytevector-copy!` procedure. R6RS and R7RS have the source and target arguments in the opposite order!

```
R6RS: (bytevector-copy! source source-start target target-start k)
R7RS: (bytevector-copy! to at from start end)
```

This can be solved by having both versions, exporting the R6RS version from `(rnrs)` and the R7RS version from `(scheme base)`.

**Comment by higepon** [comment]
I was going to work on bytevector procedures. Thanks for the heads-up!

**Comment by higepon** [comment]
Closing this https://github.com/higepon/mosh/pull/98.
