### ISSUE TITLE
file-size-in-bytes crashes on nonexistent file in developer mosh

### ISSUE THREAD

**Issue by amoe** [higepon/mosh#9]
In the `--enable-developer` build, `file-size-in-bytes` from `(mosh file)` will crash when the file does not exist.  It should raise an appropriate condition, which is the behaviour observed in the non-developer build.

The message is as such:

    ASSERT failure src/OSCompat.cpp:898: false

This is due to the use of `MOSH_ASSERT(false)` in the case where `stat` fails.  This makes the behaviour of code differ between the debug mosh and the regular mosh, which impedes debugging.

**Comment by higepon** [comment]
Hi David,
Do you think you could have pull request for this?
I think you have great point :)
