### ISSUE TITLE
Switch to `char32_t` on Windows

### ISSUE THREAD

**Issue by okuoku** [higepon/mosh#93]
Currently, we rely super-cool hack to support UCS2 platforms ie. where `sizeof(wchar_t)` == `2`.

https://github.com/higepon/mosh/blob/b8b3f6c962f806aa97c615e61a923bc41bf83cb0/src/ucs4string.cpp#L35-L61

But now, we should've have decent support of `char32_t` which finally introduced sane character handling in C++. 

- Use `U""` to `UC` implementation
- Drop UCS2 hack on Cygwin and Windows
- Replace any `L""` occurrence including tests (in particular, getoptlongU test)

`char32_t` is supported from C++11. In C++20, it mandated it is in UTF-32 form.

**Comment by higepon** [comment]
Out of curiosity can we just use char32_t for all platform?

**Comment by okuoku** [comment]
Perhaps future versions should just use `char32_t` everywhere instead of `ucs4char`, and `ucs4string` should be `std::string` of `char32_t` . 

I'm not 100% sure if we could though. Let's roll-out gradually; first, we use it where need it absolutely(= Win32).

**Comment by higepon** [comment]
Sounds good to me!
